swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Last User Transactions API
      description: API for fetching transactions emitted by user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transactions data retrieved successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions/new:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Create a Transaction API
      description: API for creating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Describe all transaction data attributes
          required: true
          schema:
            $ref: "#/definitions/NewTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transactions data retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Detail Transaction Data API
      description: API for fetching data transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: Id of transaction we are fetching
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction attributes retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Modify Transaction Data Details API
      description: API for updating data transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction data attributes
          required: true
          schema:
            $ref: "#/definitions/Transaction"
        - name: id
          in: path
          description: Id of transaction we are fetching
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction attributes retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete Transaction Data API
      description: API for deleting transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: Id of transaction we are fetching
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction attributes retrieved successfully
          schema:
            $ref: "#/definitions/DeleteResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            date:
              type: string
              format: date-time
            description:
              type: string
            amount:
              type: number
              format: double
            balance:
              type: number
              format: double
            transactionType:
              type: string
            category:
              type: string
            notes:
              type: string
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
            format: date-time
          description:
            type: string
          amount:
            type: number
            format: double
          balance:
            type: number
            format: double
          transactionType:
            type: string
          category:
            type: string
          notes:
            type: string
  NewTransaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: number
        format: double
      balance:
        type: number
        format: double
      transactionType:
        type: string
      category:
        type: string
      notes:
        type: string
  Transaction:
    type: object
    properties:
      transactionType:
        type: string
      category:
        type: string
      notes:
        type: string
  DeleteResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
